import { TuiAction } from "./types";

export const TUI_ACTIONS: TuiAction[] = [
  {
    id: "directory-copy",
    label: "Export Literal Folder Copy",
    shortLabel: "copy",
    description: "Create a literal folder export with a recursive file list and aggregated file bodies.",
    formTitle: "Export Literal Folder Copy",
    submitLabel: "Run Literal Copy",
    createFields: () => [
      {
        id: "folderPath",
        label: "Folder Path",
        type: "text",
        value: "",
        placeholder: "/absolute/path/to/folder",
      },
      {
        id: "goal",
        label: "Goal",
        type: "text",
        value: "create a literal directory copy for downstream review",
      },
      {
        id: "format",
        label: "Requested Format",
        type: "select",
        value: "both",
        options: [
          { label: "Markdown + Text", value: "both" },
          { label: "Markdown only", value: "md" },
          { label: "Text only", value: "txt" },
        ],
        hint: "When both is selected, markdown and text are written into separate folders inside the run.",
      },
      {
        id: "includeHidden",
        label: "Include Hidden",
        type: "select",
        value: "off",
        options: [
          { label: "Off", value: "off" },
          { label: "On", value: "on" },
        ],
        hint: "Include dotfiles and dot-directories such as .gitignore and .claude.",
      },
      {
        id: "omitGeneratedDirs",
        label: "Omit Generated Dirs",
        type: "select",
        value: "common",
        options: [
          { label: "Common caches/build dirs", value: "common" },
          { label: "Python caches only", value: "python" },
          { label: "Node/web caches only", value: "node" },
          { label: "Compiled build dirs only", value: "compiled" },
          { label: "Do not omit", value: "none" },
        ],
        hint: "Default skips folders like __pycache__, node_modules, .next, dist, build, target, and temp caches.",
      },
      {
        id: "chunkMarkdown",
        label: "Chunk Markdown",
        type: "select",
        value: "off",
        options: [
          { label: "Off", value: "off" },
          { label: "On", value: "on" },
        ],
        hint: "When on, write continuation markdown/text files for easier ChatGPT upload.",
      },
      {
        id: "chunkLineTarget",
        label: "Chunk Lines",
        type: "text",
        value: "10000",
        hint: "Target max rendered lines per part. Whole file bodies are never split.",
      },
      {
        id: "chunkByteTarget",
        label: "Chunk Bytes",
        type: "text",
        value: "8388608",
        hint: "Target max bytes per part. Default is 8 MB.",
      },
    ],
  },
  {
    id: "view-runs",
    label: "View Latest Runs",
    shortLabel: "runs",
    description: "Browse recent run folders and open the selected run from inside the TUI.",
    panelView: "runs",
  },
  {
    id: "task-console",
    label: "Prompt Console",
    shortLabel: "prompt",
    description: "Stage a Claude-Code-style mission prompt for future connector-backed execution.",
    formTitle: "Prompt Console",
    submitLabel: "Stage Prompt Request",
    createFields: () => [
      {
        id: "taskPrompt",
        label: "Mission Prompt",
        type: "text",
        value: "go to my instagram profile and review likely non-mutual accounts in read-only mode",
        placeholder: "Describe a future connector-backed task",
        hint: "Preview scaffold only. Arbitrary browser-control execution is not enabled yet.",
      },
      {
        id: "taskScope",
        label: "Execution Scope",
        type: "select",
        value: "browser",
        options: [
          { label: "Browser-first", value: "browser" },
          { label: "Folder-first", value: "folder" },
          { label: "Hybrid", value: "hybrid" },
        ],
        hint: "Use left/right to change the future execution scope.",
      },
      {
        id: "taskMode",
        label: "Execution Mode",
        type: "select",
        value: "preview",
        options: [
          { label: "Preview only", value: "preview" },
          { label: "Future agentic", value: "agentic" },
        ],
        hint: "This remains preview-only in v0.2.2.",
      },
    ],
  },
  {
    id: "folder",
    label: "Summarize Folder Context",
    shortLabel: "folder",
    description: "Scan an allowed folder, rank the files, and synthesize a dense context bundle.",
    formTitle: "Summarize Folder Context",
    submitLabel: "Run Folder Summary",
    createFields: () => [
      {
        id: "folderPath",
        label: "Folder Path",
        type: "text",
        value: "",
        placeholder: "/absolute/path/to/folder",
      },
      {
        id: "goal",
        label: "Goal",
        type: "text",
        value: "summarize this project folder",
      },
      {
        id: "limit",
        label: "File Limit",
        type: "text",
        value: "all",
        hint: "Use 'all' to scan the full directory or enter a number.",
      },
    ],
  },
  {
    id: "tabs",
    label: "Compile Open Tabs",
    shortLabel: "tabs",
    description: "Capture the current Chrome/Chromium tab set into one context bundle.",
    formTitle: "Compile Open Tabs",
    submitLabel: "Run Tabs Compile",
    createFields: () => [
      {
        id: "scope",
        label: "Scope",
        type: "select",
        value: "all",
        options: [
          { label: "All tabs", value: "all" },
          { label: "Current tab", value: "current" },
          { label: "Regex match", value: "match" },
        ],
        hint: "Use left/right to change scope.",
      },
      {
        id: "goal",
        label: "Goal",
        type: "text",
        value: "summarize my current browser context",
      },
      {
        id: "match",
        label: "Match Regex",
        type: "text",
        value: "",
        placeholder: "brightspace|gradescope|edstem",
        hint: "Used only when Scope is Regex match.",
      },
    ],
  },
  {
    id: "page-export",
    label: "Export Current Page",
    shortLabel: "page",
    description: "Expand the current page and export markdown, text, and PDF artifacts.",
    formTitle: "Export Current Page",
    submitLabel: "Run Page Export",
    createFields: () => [
      {
        id: "mode",
        label: "Mode",
        type: "select",
        value: "linkedin",
        options: [
          { label: "LinkedIn", value: "linkedin" },
          { label: "Generic", value: "generic" },
          { label: "Portal", value: "portal" },
          { label: "Gmail", value: "gmail" },
        ],
      },
      {
        id: "goal",
        label: "Goal",
        type: "text",
        value: "export this current page for downstream LLM use",
      },
    ],
  },
  {
    id: "launch-browser",
    label: "Launch Chrome Debug Browser",
    shortLabel: "browser",
    description: "Start a Chrome/Chromium debug session from inside Contextor using a separate automation profile.",
  },
  {
    id: "open-output",
    label: "Open Output Runs Folder",
    shortLabel: "output",
    description: "Open the output/runs directory in the OS file browser.",
  },
  {
    id: "view-logs",
    label: "View Latest Logs",
    shortLabel: "logs",
    description: "Focus the latest log tail panel.",
    panelView: "logs",
  },
  {
    id: "offline-mode",
    label: "Offline Mode",
    shortLabel: "offline",
    description: "Toggle local-only operation. Browser, network, API, and Chrome attach checks stay disabled.",
  },
  {
    id: "view-config",
    label: "View Current Config Summary",
    shortLabel: "config",
    description: "Focus the current configuration summary panel.",
    panelView: "config",
  },
];
