import fs from "node:fs/promises";
import path from "node:path";

import { ensureDirectory } from "./files";

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN_X = 36;
const START_Y = 756;
const FONT_SIZE = 8;
const LINE_HEIGHT = 10;
const MAX_LINES_PER_PAGE = 72;
const MAX_CHARS_PER_LINE = 112;

export async function renderMarkdownTextToPdf(input: {
  markdown: string;
  outputPath: string;
  title: string;
}): Promise<void> {
  await ensureDirectory(path.dirname(input.outputPath));
  const lines = buildPdfLines(input.markdown, input.title);
  const pages = chunkLines(lines, MAX_LINES_PER_PAGE);
  const pdf = buildPdfDocument(pages.length > 0 ? pages : [["Contextor directory copy"]]);
  await fs.writeFile(input.outputPath, pdf);
}

function buildPdfLines(markdown: string, title: string): string[] {
  return [
    title,
    "Generated by Contextor from markdown directory-copy output.",
    "Media and binary files are represented as metadata-only entries.",
    "",
    ...markdown.split(/\r\n|\r|\n/),
  ].flatMap((line) => wrapLine(line));
}

function wrapLine(line: string): string[] {
  const normalized = normalizePdfText(line);
  if (normalized.length <= MAX_CHARS_PER_LINE) {
    return [normalized];
  }

  const wrapped: string[] = [];
  for (let index = 0; index < normalized.length; index += MAX_CHARS_PER_LINE) {
    wrapped.push(normalized.slice(index, index + MAX_CHARS_PER_LINE));
  }
  return wrapped;
}

function chunkLines(lines: string[], size: number): string[][] {
  const pages: string[][] = [];
  for (let index = 0; index < lines.length; index += size) {
    pages.push(lines.slice(index, index + size));
  }
  return pages;
}

function buildPdfDocument(pages: string[][]): Buffer {
  const objects: string[] = [];
  const pageObjectIds: number[] = [];
  const catalogId = addObject(objects, "<< /Type /Catalog /Pages 2 0 R >>");
  const pagesId = 2;
  const fontId = 3;

  for (const [index, page] of pages.entries()) {
    const content = renderPageContent(page);
    const pageId = 4 + index * 2;
    const contentId = pageId + 1;
    pageObjectIds.push(pageId);
    addObject(
      objects,
      `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`,
      pageId,
    );
    addObject(objects, `<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream`, contentId);
  }

  addObject(
    objects,
    `<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageObjectIds.length} >>`,
    pagesId,
  );
  addObject(objects, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", fontId);

  objects.sort((left, right) => Number(left.split(" ", 1)[0]) - Number(right.split(" ", 1)[0]));

  const chunks: string[] = ["%PDF-1.4\n"];
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(chunks.join(""), "utf8"));
    chunks.push(object);
  }

  const xrefOffset = Buffer.byteLength(chunks.join(""), "utf8");
  chunks.push(`xref\n0 ${objects.length + 1}\n`);
  chunks.push("0000000000 65535 f \n");
  for (const offset of offsets.slice(1)) {
    chunks.push(`${String(offset).padStart(10, "0")} 00000 n \n`);
  }
  chunks.push(`trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`);

  return Buffer.from(chunks.join(""), "utf8");
}

function addObject(objects: string[], body: string, forcedId?: number): number {
  const id = forcedId ?? objects.length + 1;
  objects.push(`${id} 0 obj\n${body}\nendobj\n`);
  return id;
}

function renderPageContent(lines: string[]): string {
  const escapedLines = lines.map((line) => `(${escapePdfText(line)}) Tj T*`).join("\n");
  return `BT
/F1 ${FONT_SIZE} Tf
${MARGIN_X} ${START_Y} Td
${LINE_HEIGHT} TL
${escapedLines}
ET`;
}

function normalizePdfText(value: string): string {
  return value.replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "?");
}

function escapePdfText(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}
